services:
  php:
    environment:
      BITRIX_ENV_TYPE: ${BITRIX_ENV_TYPE:-production}
      PHP_FPM_MAX_CHILDREN: ${PHP_FPM_MAX_CHILDREN:-60}
      PHP_FPM_START_SERVERS: ${PHP_FPM_START_SERVERS:-12}
      PHP_FPM_MIN_SPARE_SERVERS: ${PHP_FPM_MIN_SPARE_SERVERS:-8}
      PHP_FPM_MAX_SPARE_SERVERS: ${PHP_FPM_MAX_SPARE_SERVERS:-24}
      PHP_FPM_MAX_REQUESTS: ${PHP_FPM_MAX_REQUESTS:-1000}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-1024M}
    volumes:
      - type: bind
        source: ./confs/php/project-production.ini
        target: /usr/local/etc/php/conf.d/zz-project.ini
        read_only: true
      - type: bind
        source: ./confs/php/fpm-production.conf
        target: /usr/local/etc/php-fpm.d/zz-project.conf
        read_only: true

  cron:
    environment:
      BITRIX_ENV_TYPE: ${BITRIX_ENV_TYPE:-production}
      PHP_FPM_MAX_CHILDREN: ${PHP_FPM_MAX_CHILDREN:-60}
      PHP_FPM_START_SERVERS: ${PHP_FPM_START_SERVERS:-12}
      PHP_FPM_MIN_SPARE_SERVERS: ${PHP_FPM_MIN_SPARE_SERVERS:-8}
      PHP_FPM_MAX_SPARE_SERVERS: ${PHP_FPM_MAX_SPARE_SERVERS:-24}
      PHP_FPM_MAX_REQUESTS: ${PHP_FPM_MAX_REQUESTS:-1000}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-1024M}
    volumes:
      - type: bind
        source: ./confs/php/project-production.ini
        target: /usr/local/etc/php/conf.d/zz-project.ini
        read_only: true
      - type: bind
        source: ./confs/php/fpm-production.conf
        target: /usr/local/etc/php-fpm.d/zz-project.conf
        read_only: true

  nginx:
    volumes:
      - ./confs/nginx/sites/finntrail.ru.conf:/etc/nginx/conf.d/default.conf:ro
